spring:
  application:
    name: foodtruck.backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodtruck}
    username: ${DB_USERNAME:defaultuser}
    password: ${DB_PASSWORD:defaultpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

security:
  jwt:
    secret: ${JWT_SECRET:defaultsecret}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  cors:
    origins: ${CORS_ORIGINS:http://localhost:8100}
  upload:
    dir:
      avatar: "static/avatars"
      product: "static/products"
    max-file-size: 5242880
  base:
    url: ${BASE_URL:http://localhost:8081}

server:
  port: ${PORT:8081}

scalar:
  enabled: true
  url: ${BASE_URL:http://localhost:8081}/v3/api-docs
  path: /docs
  showSidebar: true
  hideModels: false
  theme: default
  layout: modern

firebase:
  bucket-name: ${FIREBASE_BUCKET_NAME:default-bucket}
  service-account: ${FIREBASE_SERVICE_ACCOUNT:file:./firebase-credentials.json}
